queue_rules:
  - name: default
    merge_method: squash
    update_method: rebase

pull_request_rules:
  - name: Auto-merge Dependabot patch updates
    conditions:
      - author=dependabot[bot]
      - "-title~=major"
      - check-success=build
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default

  - name: Flag Dependabot major updates
    conditions:
      - author=dependabot[bot]
      - "title~=major"
    actions:
      label:
        add:
          - needs-review
          - major-update

  - name: Clean up merged branches
    conditions:
      - merged
    actions:
      delete_head_branch: {}
